# Site settings
title: Instant Siding Prices
email: info@instantsidingprices.com
description: >-
  Get instant pricing estimates for your siding remodel project. Professional siding installation services with transparent pricing and exceptional quality.
baseurl: "/siding-leads" # the subpath of your site, e.g. /blog
url: "https://tim-amredev.github.io" # the base hostname & protocol for your site
twitter_username: instantsiding
github_username: instantsiding

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

